version: "3.9"

services:
  api-nodejs:
    container_name: api-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 3333:3333
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    restart: on-failure
    user: root
    volumes:
      - ./.docker/jenkins/data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
